blank_issues_enabled: false
contact_links:
  - name: 🐛 Bug Report
    url: https://github.com/coze-dev/coze-loop/issues/new?template=bug_report.yml
    about: Report a bug to help us improve Coze Loop
  - name: ✨ Feature Request
    url: https://github.com/coze-dev/coze-loop/issues/new?template=feature_request.yml
    about: Suggest a new feature for Coze Loop
  - name: 🔧 Question/Help
    url: https://github.com/coze-dev/coze-loop/discussions
    about: Ask questions or get help from the community
